# Generated by Django 2.2.6 on 2019-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(max_length=15)),
                ('shape', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
    ]
